"""
Compliance Router - IT Asset Manager v2.7.5
Serves compliance results generated by the external compliance container.
Provides auxiliary endpoints for the compliance container to test encryption and DB.
"""

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from sqlalchemy import text
from pathlib import Path

from app.api.deps import get_db, get_current_active_admin
from app.models.user import User
from app.services.compliance_service import get_latest_results, list_pdf_reports, get_guide_info

router = APIRouter(prefix="/compliance", tags=["compliance"])

COMPLIANCE_DIR = Path("/app/data/compliance")


@router.get("/results")
def get_results(
    current_user: User = Depends(get_current_active_admin),
):
    """
    Returns the latest compliance test results from the external container.
    Reads data/compliance/latest_report.json.
    Solo admin.
    """
    results = get_latest_results()
    if not results:
        return {
            "status": "no_results",
            "message": "Nessun test eseguito. Segui la guida per lanciare il test dal terminale.",
        }
    return results


@router.get("/guide")
def get_compliance_guide(
    current_user: User = Depends(get_current_active_admin),
):
    """
    Returns host connection info and commands for running the compliance test.
    Used by the frontend to display copy-paste instructions.
    Solo admin.
    """
    return get_guide_info()


@router.get("/reports")
def get_report_list(
    current_user: User = Depends(get_current_active_admin),
):
    """
    Lists all available compliance PDF reports, newest first.
    Solo admin.
    """
    return {"reports": list_pdf_reports()}


@router.get("/download-report/{filename}")
def download_report(
    filename: str,
    current_user: User = Depends(get_current_active_admin),
):
    """
    Download a compliance PDF report.
    Solo admin.
    """
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(status_code=400, detail="Nome file non valido")
    file_path = COMPLIANCE_DIR / filename
    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail="File non trovato")
    return FileResponse(
        path=str(file_path),
        media_type="application/pdf",
        filename=filename,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/encryption-check")
def encryption_check(
    current_user: User = Depends(get_current_active_admin),
):
    """
    Auxiliary endpoint for the external compliance container.
    Verifies that the encryption at rest system works correctly.
    Runs 3 tests: encrypt, decrypt, backward compatibility.
    Solo admin.
    """
    from app.core.log_encryption import encrypt_log, decrypt_log, is_encrypted
    results = []
    try:
        encrypted = encrypt_log("test_data_123")
        results.append({
            "name": "encrypt_log produce token Fernet",
            "passed": bool(is_encrypted(encrypted)),
            "detail": ""
        })
        decrypted = decrypt_log(encrypted)
        results.append({
            "name": "decrypt_log ritorna plaintext",
            "passed": decrypted == "test_data_123",
            "detail": ""
        })
        plain = decrypt_log("dato non criptato")
        results.append({
            "name": "Backward compat: plaintext ritornato invariato",
            "passed": plain == "dato non criptato",
            "detail": ""
        })
    except Exception as e:
        error_detail = str(e)
        for name in ["encrypt_log produce token Fernet", "decrypt_log ritorna plaintext", "Backward compat: plaintext ritornato invariato"]:
            if not any(r["name"] == name for r in results):
                results.append({"name": name, "passed": False, "detail": error_detail})
    return {"tests": results}


@router.get("/db-check")
def db_check(
    current_user: User = Depends(get_current_active_admin),
    db: Session = Depends(get_db),
):
    """
    Auxiliary endpoint for the external compliance container.
    Verifies that the database connection works.
    Solo admin.
    """
    try:
        db.execute(text("SELECT 1"))
        return {"connected": True, "detail": ""}
    except Exception as e:
        return {"connected": False, "detail": str(e)}
