"""
Compliance Service - IT Asset Manager v2.7.5
Reads compliance results generated by the external compliance container.
The compliance container runs tests independently and saves reports to data/compliance/.
"""

import json
from pathlib import Path
from typing import Optional, Dict, List
import logging

from app.core.config import settings

logger = logging.getLogger(__name__)

COMPLIANCE_DIR = Path("/app/data/compliance")


def get_latest_results() -> Optional[Dict]:
    """Read the latest compliance test results from the external container output."""
    path = COMPLIANCE_DIR / "latest_report.json"
    if not path.exists():
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        logger.error("Error reading compliance results: %s", e)
        return None


def list_pdf_reports() -> List[str]:
    """List all available compliance PDF reports, newest first."""
    if not COMPLIANCE_DIR.exists():
        return []
    return sorted(
        [f.name for f in COMPLIANCE_DIR.glob("compliance_report_*.pdf")],
        reverse=True,
    )


def get_guide_info() -> Dict:
    """Return host info for the compliance guide displayed in the UI."""
    host_ip = settings.host_ip
    project_path = settings.project_path
    ssh_user = settings.ssh_user
    return {
        "host_ip": host_ip,
        "project_path": project_path,
        "ssh_user": ssh_user,
        "ssh_command": f"ssh {ssh_user}@{host_ip}" if ssh_user and host_ip else "",
        "test_command": f"cd {project_path} && docker compose run --rm compliance" if project_path else "docker compose run --rm compliance",
    }
